kind: pipeline
name: default

steps:
- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
      - src/*.xml
      - src/*.mpackage
  when:
    event: tag