kind: pipeline
name: default

steps:
- name: version-is-commit
  image: busybox
  commands:
    - |
      echo { \"package\": \"tec-mudlet-integration\", \"version\": \"${DRONE_COMMIT_SHA:0:8}\" } > mfile
  when:
    event: push
- name: version-is-tag
  image: busybox
  commands:
    - |
      echo { \"package\": \"tec-mudlet-integration\", \"version\": \"${DRONE_TAG}\" } > mfile
  when:
    event: tag
- name: move-files
  image: busybox
  commands:
    - cat mfile
    - mkdir src/resources
    - mv src/**.* src/resources
    - cp mfile src/resources
    - ls
    - ls src
    - ls src/resources
- name: build-mpackage
  image: demonnic/muddler
- name: sanity-check
  image: busybox
  commands:
    - ls build
- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: build/tec-mudlet-integration.mpackage
  when:
    event: tag
