# # This is a basic workflow to help you get started with Actions

# name: CI

# # Controls when the action will run. Triggers the workflow on push or pull request
# # events but only for the master branch
# on:
#   push:
#     branches: [ develop ]
# jobs:
#   build:
#     name: Create Release
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2        
#       - name: Get Latest Version
#         id: get_version
#         uses: pozetroninc/github-action-get-latest-release@master
#         with:
#             repository: TheEternalCitizens/mudlet-integration
#       - name: Bump Versions
#         id: version_bump
#         run: |
#           VERSION="${{ steps.get_version.outputs.release }}"
#           echo "Version $VERSION"
#           export NEXT_VERSION=$(awk -F. -v OFS=. '{$NF++;print}' <<< "$VERSION")
#           echo "Next Version $NEXT_VERISON"
#           echo "::set-env name=NEXT_VERSION::$NEXT_VERSION"
#       - name: Create Release
#         id: create_release
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
#         with:
#           tag_name: ${{ github.ref }}
#           release_name: $NEXT_VERSION
#           body: |
#             Changes in this Release
#             - First Change
#             - Second Change
#           draft: false
#           prerelease: true
