# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ release ]
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2        
      - name: Get Latest Version
        id: get_version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
            repository: TheEternalCitizens/mudlet-integration
      - name: Bump Versions
        run: |
           NEXT_VERSION= perl -pe 's/^((\d+\.)*)(\d+)(.*)$/$1.($3+1).$4/e' < ${{ steps.get_version.outputs.release }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          release_name: ${{ NEXT_VERSION }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: true
